export const LOGIN_CLIENT_REQUEST = "LOGIN_CLIENT_REQUEST";
export const LOGIN_CLIENT_ERROR = "LOGIN_CLIENT_ERROR";
export const LOGIN_CLIENT_SUCCESS = "LOGIN_CLIENT_SUCCESS";


export const REGISTER_CLIENT_SUCCESS = " REGISTER_CLIENT_SUCCESS";
export const REGISTER_CLIENT_ERROR = "REGISTER_CLIENT_ERROR";
export const REGISTER_CLIENT_REQUEST = "REGISTER_CLIENT_REQUEST";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS";
export const GET_INFO_REQUEST = "GET_INFO_REQUEST";
export const GET_INFO_ERROR = "GET_INFO_ERROR";

export const UPDATE_INFO_ERROR = "UPDATE_INFO_ERROR";
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";
export const UPDATE_INFO_REQUEST = "UPDATE_INFO_REQUEST";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";

export const SET_USER_ROLE_REQUEST = "SET_USER_ROLE_REQUEST";
export const SET_USER_ROLE_ERROR = "SET_USER_ROLE_ERROR";
export const SET_USER_ROLE_SUCCESS = "SET_USER_ROLE_SUCCESS";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USER_REQUEST = "GET_USER_REQUEST";